apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  appsettings.json: |-
{{- if .Values.appsettings }}
{{ tpl .Values.appsettings . | indent 4 }}
{{- end }}
  nlog.config: |-
{{- if .Values.nlog }}
{{ tpl .Values.nlog . | indent 4 }}
{{- end }}
