apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  appsettings.json: |-
{{ .Files.Get "appsettings.json" | indent 4}}
  nlog.config: |-
{{ .Files.Get "nlog.config" | indent 4}}
