apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-appsettings-configmap
data:
  appsettings.json: |-
{{ .Files.Get "appsettings.json" | indent 4}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nlog-configmap
data:
  nlog.config: |-
{{ .Files.Get "nlog.config" | indent 4}}
