version: '3'

services:
  db:
    container_name: db
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234jk
      MYSQL_DATABASE: accountDb
  api:
    container_name: api
    image: blackhorseya/learn-dotnet:latest
    ports:
      - 8080:80
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./nlog.config:/app/nlog.config
