version: '3'

services:
  db:
    container_name: accountDb
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: accountDb
    volumes:
      - /Users/doggy/docker/data/accountDb:/var/lib/mysql
  api:
    container_name: learn-dotnet-api
    image: blackhorseya/learn-dotnet:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./config/local/appsettings.json:/app/appsettings.json
      - ./config/local/nlog.config:/app/nlog.config
