// <auto-generated />
using System;
using Doggy.Learning.Auth.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Doggy.Learning.Auth.Domain.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20191117040344_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Doggy.Learning.Auth.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Doggy.Learning.Auth.Domain.Entities.GroupRoleMap", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("GroupId");

                    b.HasKey("RoleId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupRoleMap");
                });

            modelBuilder.Entity("Doggy.Learning.Auth.Domain.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Doggy.Learning.Auth.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Doggy.Learning.Auth.Domain.Entities.RoleModuleMap", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("ModuleId");

                    b.HasKey("RoleId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("RoleModuleMap");
                });

            modelBuilder.Entity("Doggy.Learning.Auth.Domain.Entities.RoleServiceMap", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("ServiceId");

                    b.HasKey("RoleId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("RoleServiceMap");
                });

            modelBuilder.Entity("Doggy.Learning.Auth.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Doggy.Learning.Auth.Domain.Entities.GroupRoleMap", b =>
                {
                    b.HasOne("Doggy.Learning.Auth.Domain.Entities.Group", "Group")
                        .WithMany("Roles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Doggy.Learning.Auth.Domain.Entities.Role", "Role")
                        .WithMany("Groups")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Doggy.Learning.Auth.Domain.Entities.RoleModuleMap", b =>
                {
                    b.HasOne("Doggy.Learning.Auth.Domain.Entities.Module", "Module")
                        .WithMany("Roles")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Doggy.Learning.Auth.Domain.Entities.Role", "Role")
                        .WithMany("Modules")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Doggy.Learning.Auth.Domain.Entities.RoleServiceMap", b =>
                {
                    b.HasOne("Doggy.Learning.Auth.Domain.Entities.Role", "Role")
                        .WithMany("Services")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Doggy.Learning.Auth.Domain.Entities.Service", "Service")
                        .WithMany("Roles")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
